### ISSUE TITLE
"$ qualifier for variables" already implemented

### ISSUE THREAD

**Issue by tarsius** [vermiculus/graphql.el#5]
The README lists "$ qualifier for variables (graphql--encode-object)" under Planned, but that's already implemented, or am I missing something?

**Comment by vermiculus** [comment]
Ack, you're right; nice catch!

**Comment by vermiculus** [comment]
On the subject of the above mess… shouldn't `M-w` on a commit in a magit-log buffer copy the hash of the commit at point?

**Comment by tarsius** [comment]
`C-w` does.
